config/routes.rb
Chirpl::Application.routes.draw do
  resources :output_keys

  resources :playlists

  resources :outputs

  resources :inputs

  resources :jobs

  

end

app/models/input.rb
class Input < ActiveRecord::Base
end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  before_action :set_input, only: [:show, :edit, :update, :destroy]

  # GET /inputs
  # GET /inputs.json
  def index
    @inputs = Input.all
  end

  # GET /inputs/1
  # GET /inputs/1.json
  def show
  end

  # GET /inputs/new
  def new
    @input = Input.new
  end

  # GET /inputs/1/edit
  def edit
  end

  # POST /inputs
  # POST /inputs.json
  def create
    @input = Input.new(input_params)

    respond_to do |format|
      if @input.save
        format.html { redirect_to @input, notice: 'Input was successfully created.' }
        format.json { render action: 'show', status: :created, location: @input }
      else
        format.html { render action: 'new' }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inputs/1
  # PATCH/PUT /inputs/1.json
  def update
    respond_to do |format|
      if @input.update(input_params)
        format.html { redirect_to @input, notice: 'Input was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @input.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inputs/1
  # DELETE /inputs/1.json
  def destroy
    @input.destroy
    respond_to do |format|
      format.html { redirect_to inputs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_input
      @input = Input.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def input_params
      params.require(:input).permit(:key, :frameRate, :resolution, :aspectRatio, :interlaced, :container, :job_id)
    end
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/views/inputs/_form.html.erb
<%= form_for(@input) do |f| %>
  <% if @input.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@input.errors.count, "error") %> prohibited this input from being saved:</h2>

      <ul>
      <% @input.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :frameRate %><br>
    <%= f.text_field :frameRate %>
  </div>
  <div class="field">
    <%= f.label :resolution %><br>
    <%= f.text_field :resolution %>
  </div>
  <div class="field">
    <%= f.label :aspectRatio %><br>
    <%= f.text_field :aspectRatio %>
  </div>
  <div class="field">
    <%= f.label :interlaced %><br>
    <%= f.text_field :interlaced %>
  </div>
  <div class="field">
    <%= f.label :container %><br>
    <%= f.text_field :container %>
  </div>
  <div class="field">
    <%= f.label :job_id %><br>
    <%= f.number_field :job_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inputs/edit.html.erb
<h1>Editing input</h1>

<%= render 'form' %>

<%= link_to 'Show', @input %> |
<%= link_to 'Back', inputs_path %>

app/views/inputs/index.html.erb
<h1>Listing inputs</h1>

<table>
  <thead>
    <tr>
      <th>Key</th>
      <th>Framerate</th>
      <th>Resolution</th>
      <th>Aspectratio</th>
      <th>Interlaced</th>
      <th>Container</th>
      <th>Job</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inputs.each do |input| %>
      <tr>
        <td><%= input.key %></td>
        <td><%= input.frameRate %></td>
        <td><%= input.resolution %></td>
        <td><%= input.aspectRatio %></td>
        <td><%= input.interlaced %></td>
        <td><%= input.container %></td>
        <td><%= input.job_id %></td>
        <td><%= link_to 'Show', input %></td>
        <td><%= link_to 'Edit', edit_input_path(input) %></td>
        <td><%= link_to 'Destroy', input, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Input', new_input_path %>

app/views/inputs/new.html.erb
<h1>New input</h1>

<%= render 'form' %>

<%= link_to 'Back', inputs_path %>

app/views/inputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Key:</strong>
  <%= @input.key %>
</p>

<p>
  <strong>Framerate:</strong>
  <%= @input.frameRate %>
</p>

<p>
  <strong>Resolution:</strong>
  <%= @input.resolution %>
</p>

<p>
  <strong>Aspectratio:</strong>
  <%= @input.aspectRatio %>
</p>

<p>
  <strong>Interlaced:</strong>
  <%= @input.interlaced %>
</p>

<p>
  <strong>Container:</strong>
  <%= @input.container %>
</p>

<p>
  <strong>Job:</strong>
  <%= @input.job_id %>
</p>

<%= link_to 'Edit', edit_input_path(@input) %> |
<%= link_to 'Back', inputs_path %>