config/routes.rb
Chirpl::Application.routes.draw do
  resources :output_keys

  resources :playlists

  resources :outputs

  resources :inputs

  resources :jobs

  

end

app/models/output_key.rb
class OutputKey < ActiveRecord::Base
end

app/controllers/output_keys_controller.rb
class OutputKeysController < ApplicationController
  before_action :set_output_key, only: [:show, :edit, :update, :destroy]

  # GET /output_keys
  # GET /output_keys.json
  def index
    @output_keys = OutputKey.all
  end

  # GET /output_keys/1
  # GET /output_keys/1.json
  def show
  end

  # GET /output_keys/new
  def new
    @output_key = OutputKey.new
  end

  # GET /output_keys/1/edit
  def edit
  end

  # POST /output_keys
  # POST /output_keys.json
  def create
    @output_key = OutputKey.new(output_key_params)

    respond_to do |format|
      if @output_key.save
        format.html { redirect_to @output_key, notice: 'Output key was successfully created.' }
        format.json { render action: 'show', status: :created, location: @output_key }
      else
        format.html { render action: 'new' }
        format.json { render json: @output_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /output_keys/1
  # PATCH/PUT /output_keys/1.json
  def update
    respond_to do |format|
      if @output_key.update(output_key_params)
        format.html { redirect_to @output_key, notice: 'Output key was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @output_key.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /output_keys/1
  # DELETE /output_keys/1.json
  def destroy
    @output_key.destroy
    respond_to do |format|
      format.html { redirect_to output_keys_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_output_key
      @output_key = OutputKey.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def output_key_params
      params.require(:output_key).permit(:name, :playlist_id)
    end
end

app/helpers/output_keys_helper.rb
module OutputKeysHelper
end

app/views/output_keys/_form.html.erb
<%= form_for(@output_key) do |f| %>
  <% if @output_key.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@output_key.errors.count, "error") %> prohibited this output_key from being saved:</h2>

      <ul>
      <% @output_key.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :playlist_id %><br>
    <%= f.number_field :playlist_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/output_keys/edit.html.erb
<h1>Editing output_key</h1>

<%= render 'form' %>

<%= link_to 'Show', @output_key %> |
<%= link_to 'Back', output_keys_path %>

app/views/output_keys/index.html.erb
<h1>Listing output_keys</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Playlist</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @output_keys.each do |output_key| %>
      <tr>
        <td><%= output_key.name %></td>
        <td><%= output_key.playlist_id %></td>
        <td><%= link_to 'Show', output_key %></td>
        <td><%= link_to 'Edit', edit_output_key_path(output_key) %></td>
        <td><%= link_to 'Destroy', output_key, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Output key', new_output_key_path %>

app/views/output_keys/new.html.erb
<h1>New output_key</h1>

<%= render 'form' %>

<%= link_to 'Back', output_keys_path %>

app/views/output_keys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @output_key.name %>
</p>

<p>
  <strong>Playlist:</strong>
  <%= @output_key.playlist_id %>
</p>

<%= link_to 'Edit', edit_output_key_path(@output_key) %> |
<%= link_to 'Back', output_keys_path %>