config/routes.rb
Chirpl::Application.routes.draw do
  resources :output_keys

  resources :playlists

  resources :outputs

  resources :inputs

  resources :jobs

  

end

app/models/output.rb
class Output < ActiveRecord::Base
end

app/controllers/outputs_controller.rb
class OutputsController < ApplicationController
  before_action :set_output, only: [:show, :edit, :update, :destroy]

  # GET /outputs
  # GET /outputs.json
  def index
    @outputs = Output.all
  end

  # GET /outputs/1
  # GET /outputs/1.json
  def show
  end

  # GET /outputs/new
  def new
    @output = Output.new
  end

  # GET /outputs/1/edit
  def edit
  end

  # POST /outputs
  # POST /outputs.json
  def create
    @output = Output.new(output_params)

    respond_to do |format|
      if @output.save
        format.html { redirect_to @output, notice: 'Output was successfully created.' }
        format.json { render action: 'show', status: :created, location: @output }
      else
        format.html { render action: 'new' }
        format.json { render json: @output.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outputs/1
  # PATCH/PUT /outputs/1.json
  def update
    respond_to do |format|
      if @output.update(output_params)
        format.html { redirect_to @output, notice: 'Output was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @output.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outputs/1
  # DELETE /outputs/1.json
  def destroy
    @output.destroy
    respond_to do |format|
      format.html { redirect_to outputs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_output
      @output = Output.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def output_params
      params.require(:output).permit(:id, :presetId, :key, :thumbnailPattern, :rotate, :segmentDuration, :status, :duration, :width, :height, :job_id)
    end
end

app/helpers/outputs_helper.rb
module OutputsHelper
end

app/views/outputs/_form.html.erb
<%= form_for(@output) do |f| %>
  <% if @output.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@output.errors.count, "error") %> prohibited this output from being saved:</h2>

      <ul>
      <% @output.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :presetId %><br>
    <%= f.text_field :presetId %>
  </div>
  <div class="field">
    <%= f.label :key %><br>
    <%= f.text_field :key %>
  </div>
  <div class="field">
    <%= f.label :thumbnailPattern %><br>
    <%= f.text_field :thumbnailPattern %>
  </div>
  <div class="field">
    <%= f.label :rotate %><br>
    <%= f.text_field :rotate %>
  </div>
  <div class="field">
    <%= f.label :segmentDuration %><br>
    <%= f.text_field :segmentDuration %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :duration %><br>
    <%= f.text_field :duration %>
  </div>
  <div class="field">
    <%= f.label :width %><br>
    <%= f.text_field :width %>
  </div>
  <div class="field">
    <%= f.label :height %><br>
    <%= f.text_field :height %>
  </div>
  <div class="field">
    <%= f.label :job_id %><br>
    <%= f.number_field :job_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/outputs/edit.html.erb
<h1>Editing output</h1>

<%= render 'form' %>

<%= link_to 'Show', @output %> |
<%= link_to 'Back', outputs_path %>

app/views/outputs/index.html.erb
<h1>Listing outputs</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Presetid</th>
      <th>Key</th>
      <th>Thumbnailpattern</th>
      <th>Rotate</th>
      <th>Segmentduration</th>
      <th>Status</th>
      <th>Duration</th>
      <th>Width</th>
      <th>Height</th>
      <th>Job</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @outputs.each do |output| %>
      <tr>
        <td><%= output.id %></td>
        <td><%= output.presetId %></td>
        <td><%= output.key %></td>
        <td><%= output.thumbnailPattern %></td>
        <td><%= output.rotate %></td>
        <td><%= output.segmentDuration %></td>
        <td><%= output.status %></td>
        <td><%= output.duration %></td>
        <td><%= output.width %></td>
        <td><%= output.height %></td>
        <td><%= output.job_id %></td>
        <td><%= link_to 'Show', output %></td>
        <td><%= link_to 'Edit', edit_output_path(output) %></td>
        <td><%= link_to 'Destroy', output, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Output', new_output_path %>

app/views/outputs/new.html.erb
<h1>New output</h1>

<%= render 'form' %>

<%= link_to 'Back', outputs_path %>

app/views/outputs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @output.id %>
</p>

<p>
  <strong>Presetid:</strong>
  <%= @output.presetId %>
</p>

<p>
  <strong>Key:</strong>
  <%= @output.key %>
</p>

<p>
  <strong>Thumbnailpattern:</strong>
  <%= @output.thumbnailPattern %>
</p>

<p>
  <strong>Rotate:</strong>
  <%= @output.rotate %>
</p>

<p>
  <strong>Segmentduration:</strong>
  <%= @output.segmentDuration %>
</p>

<p>
  <strong>Status:</strong>
  <%= @output.status %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @output.duration %>
</p>

<p>
  <strong>Width:</strong>
  <%= @output.width %>
</p>

<p>
  <strong>Height:</strong>
  <%= @output.height %>
</p>

<p>
  <strong>Job:</strong>
  <%= @output.job_id %>
</p>

<%= link_to 'Edit', edit_output_path(@output) %> |
<%= link_to 'Back', outputs_path %>